### ISSUE TITLE
Help me Add domain.

### ISSUE THREAD

**Issue by wszmk** [dee-al/domain.dee.al#52]
Hello! I can't https://github.com/dee-al/domain.dee.al/tree/main/domain/dee.al/github.json Add my domain name. I hope you can https://github.com/dee-al/domain.dee.al/tree/main/domain/dee.al/github.json Add my domain name in the format you said:
{
"koneksi": "CNAME",
"hostku": "node",
"target": "nodecn.github.io"
}
I hope you can help me add [github. json]（ https://github.com/dee-al/domain.dee.al/tree/main/domain/dee.al/github.json ）Insert this domain name

thank you.

**Comment by nodecn** [comment]
ok?

**Comment by wszmk** [comment]
no,add domain me add domain.
